
package com.application.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.6.13
 * Tue Sep 03 08:50:30 WAT 2019
 * Generated source version: 2.6.13
 */

@XmlRootElement(name = "fetchUserResponse", namespace = "http://application.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "fetchUserResponse", namespace = "http://application.com/")

public class FetchUserResponse {

    @XmlElement(name = "RESPONSE")
    private com.application.fetchUser.FetchUserResponse RESPONSE;

    public com.application.fetchUser.FetchUserResponse getRESPONSE() {
        return this.RESPONSE;
    }

    public void setRESPONSE(com.application.fetchUser.FetchUserResponse newRESPONSE)  {
        this.RESPONSE = newRESPONSE;
    }

}

